disease_names = {
    'ADHD': 'Attention-Deficit/Hyperactivity Disorder',
    'ASD': 'Autistic Spectrum Disorders',
    'AD': "Alzheimer's Disease",
    'MCI': 'Mild Cognitive Impairment',
    'DM': 'Dementia',
    'MDD': 'Major Depression Disorder',
    'ANX': 'Anxiety',
    'ODD': 'Oppositional Defiant Disorder',
    'OCD': 'Obsessive-Compulsive Disorder',
    'LD': 'Language Disorder',
    'SLD': 'Specific Learning Disorder',
    'ENU': 'Enuresis',
    'ID': 'Intellectual Disability',
    'PTSD': 'Post-Traumatic Stress Disorder',
    'ECP': 'Encopresis',
    'PDD': 'Dysthymia',
    'TS': 'Tourette Syndrome',
    'AJD': 'Adjustment Disorder',
    'PTD': 'Provisional Tic Disorder',
    'MD': 'Motor Disorder',
    'SSD': 'Speech Sound Disorder',
    'CD': 'Communication Disorder',
    'CUD': 'Cocaine Use Disorder',
    'SCHZ': 'Schizophrenia',
    'BP': 'Bipolar Disorder',
    'None': 'None'
}